// ==========================================
// 0. ข้อมูลปัญหาและวิธีแก้ไขระดับอำเภอทั้ง 23 พื้นที่
// ==========================================
const districtInsightsData = {
    "ขนอม": {
        th: { problems: ["ควันดำจากเรือประมงและเรือท่องเที่ยว", "ฝุ่นจากรถยนต์และการคมนาคม", "การเผาเศษวัสดุทางการเกษตร"], solutions: ["ตรวจสภาพเครื่องยนต์เรือและรถยนต์อย่างสม่ำเสมอ", "ลดการเผาในพื้นที่เกษตร", "เพิ่มพื้นที่สีเขียวและต้นไม้ริมถนน"] },
        en: { problems: ["Black smoke from fishing and tourist vessels", "Dust from cars and general transit", "Burning of leftover agricultural waste"], solutions: ["Regularly service boat and car engines", "Reduce open fires in agricultural zones", "Grow more roadside trees and green shields"] }
    },
    "สิชล": {
        th: { problems: ["ควันจากเรือประมง", "ฝุ่นจากรถยนต์", "การเผาเศษวัสดุทางการเกษตร"], solutions: ["ควบคุมควันดำจากเรือและรถยนต์", "ส่งเสริมการทำปุ๋ยหมักแทนการเผา", "เพิ่มการตรวจวัดคุณภาพอากาศ"] },
        en: { problems: ["Emissions from fishing vessels", "Dust generated by vehicles", "Burning of agricultural biomass"], solutions: ["Strictly control black smoke from transport", "Promote composting organic waste", "Deploy extra air quality monitors"] }
    },
    "ท่าศาลา": {
        th: { problems: ["ฝุ่นจากรถยนต์", "ควันจากเรือประมง", "การเผาเศษวัสดุทางการเกษตร"], solutions: ["ลดการเผาในพื้นที่เกษตร", "ตรวจสภาพรถยนต์และเรือ", "เพิ่มพื้นที่สีเขียวในชุมชน"] },
        en: { problems: ["Exhaust dust from cars", "Smoke from fishing fleets", "Agricultural residue burning"], solutions: ["Enforce zero burning on farms", "Mandate routine car and vessel inspections", "Expand urban forests and community parks"] }
    },
    "ปากพนัง": {
        th: { problems: ["โรงงานแปรรูปปลา", "ควันจากเรือประมง", "ฝุ่นจากรถยนต์"], solutions: ["ติดตั้งระบบบำบัดฝุ่นและกลิ่นในโรงงาน", "ควบคุมการปล่อยมลพิษจากเรือ", "ลดการเผาในพื้นที่เกษตร"] },
        en: { problems: ["Fish processing plant pollution", "Emissions from active fishing boats", "Vehicle exhaust dust"], solutions: ["Install dust and odor filters in factories", "Regulate standard marine emissions", "Mitigate seasonal farm fires"] }
    },
    "หัวไทร": {
        th: { problems: ["ควันจากเรือประมง", "ฝุ่นจากรถยนต์", "การเผาเศษวัสดุทางการเกษตร"], solutions: ["ลดการเผาในพื้นที่โล่ง", "ตรวจสภาพเครื่องยนต์เรือและรถ", "เพิ่มพื้นที่สีเขียว"] },
        en: { problems: ["Smoke from standard fishing boats", "Street vehicle emissions", "Crop waste burning"], solutions: ["Ban open-air waste burning", "Perform technical checks on cars & boats", "Develop more neighborhood green zones"] }
    },
    "เชียรใหญ่": {
        th: { problems: ["การเผาเศษวัสดุทางการเกษตร", "ฝุ่นจากการคมนาคม"], solutions: ["ส่งเสริมเกษตรปลอดการเผา", "ควบคุมควันดำจากรถยนต์", "รณรงค์ลดการเผาในชุมชน"] },
        en: { problems: ["Agricultural waste burning", "Transit road dust"], solutions: ["Pioneer zero-burn smart farming", "Filtre out dark automotive exhaust", "Launch local anti-burning campaigns"] }
    },
    "ลานสกา": {
        th: { problems: ["การเผากิ่งไม้และใบไม้ในสวน", "ฝุ่นจากสารเคมีทางการเกษตร"], solutions: ["ทำปุ๋ยหมักจากเศษพืช", "ลดการใช้สารเคมี", "ส่งเสริมเกษตรอินทรีย์"] },
        en: { problems: ["Burning of orchard twigs and leaves", "Chemical spray residues from farms"], solutions: ["Convert organic waste to bio-compost", "Minimize synthetic agrochemical use", "Drive transition to organic farming"] }
    },
    "พรหมคีรี": {
        th: { problems: ["การเผาในสวนผลไม้และสวนยาง", "ฝุ่นจากการทำเกษตร"], solutions: ["งดเผาเศษวัสดุทางการเกษตร", "ส่งเสริมการไถกลบ", "ลดการใช้สารเคมี"] },
        en: { problems: ["Fires in fruit and rubber orchards", "Soil dust from farm preparations"], solutions: ["Stop burning post-harvest waste", "Advocate eco-friendly stubble plowing", "Cut down toxic farm chemicals"] }
    },
    "นบพิตำ": {
        th: { problems: ["การเผาเศษวัสดุทางการเกษตร", "ฝุ่นจากสารเคมี"], solutions: ["ส่งเสริมเกษตรอินทรีย์", "ลดการเผาในสวน", "อนุรักษ์พื้นที่ป่า"] },
        en: { problems: ["Burning crop leftovers", "Agricultural chemical mist"], solutions: ["Expand clean organic farming networks", "Halt seasonal orchard burnings", "Protect surrounding natural forests"] }
    },
    "พิปูน": {
        th: { problems: ["การเผาในสวนยางพารา", "ฝุ่นจากกิจกรรมเกษตร"], solutions: ["งดการเผาในสวน", "ทำปุ๋ยหมักจากเศษพืช", "เฝ้าระวังไฟป่า"] },
        en: { problems: ["Leaf clearing fires in rubber woods", "Agri-activity particulate dispersion"], solutions: ["Ban open fires inside plantations", "Repurpose leaf litter into compost", "Form local forest fire watch teams"] }
    },
    "ฉวาง": {
        th: { problems: ["โรงงานแปรรูปไม้ยาง", "การเผาเศษวัสดุทางการเกษตร"], solutions: ["ติดตั้งระบบกรองฝุ่นในโรงงาน", "ลดการเผาในสวน", "เพิ่มการตรวจวัดคุณภาพอากาศ"] },
        en: { problems: ["Rubberwood mills particulate output", "Farm waste open burnings"], solutions: ["Enforce high-grade industrial air filters", "Reduce clearing fires in fields", "Install permanent AQI tracking units"] }
    },
    "ถ้ำพรรณรา": {
        th: { problems: ["การเผาเศษวัสดุทางการเกษตร", "ฝุ่นจากสารเคมี"], solutions: ["ส่งเสริมการทำปุ๋ยหมัก", "ลดการใช้สารเคมี", "ป้องกันไฟป่า"] },
        en: { problems: ["Burning farm residues", "Chemical dust particles"], solutions: ["Educate community on dynamic composting", "Scale back chemical fertilizers", "Build strategic forest firebreaks"] }
    },
    "ช้างกลาง": {
        th: { problems: ["โรงงานแปรรูปไม้ยาง", "การเผาในสวนผลไม้และสวนยาง"], solutions: ["ควบคุมฝุ่นจากโรงงาน", "ลดการเผาในพื้นที่เกษตร", "ส่งเสริมเกษตรยั่งยืน"] },
        en: { problems: ["Wood processing plant soot", "Burning in mixed fruit and rubber plots"], solutions: ["Tighten factory emissions caps", "Discourage open field fires", "Nurture holistic sustainable agriculture"] }
    },
    "จุฬาภรณ์": {
        th: { problems: ["โรงงานแปรรูปไม้ยาง", "การเผาเศษวัสดุทางการเกษตร"], solutions: ["ติดตั้งระบบกรองฝุ่น", "งดการเผาในสวน", "เพิ่มพื้นที่สีเขียว"] },
        en: { problems: ["Local rubberwood factory dust", "Crop clearing burnings"], solutions: ["Mandate advanced scrubber systems", "Prohibit plantation clearing fires", "Fund regional afforestation projects"] }
    },
    "เมือง": {
        th: { problems: ["การจราจรหนาแน่น", "ฝุ่นจากถนน", "ควันจากรถยนต์"], solutions: ["ลดปัญหาการจราจรติดขัด", "ตรวจสภาพรถยนต์", "ล้างถนนและเพิ่มพื้นที่สีเขียว"] },
        en: { problems: ["Heavy vehicle traffic grids", "Resuspended road dust", "Automobile exhaust smoke"], solutions: ["Optimize city transit flows", "Strictly filter polluting old cars", "Wash city streets and plant dense greenery"] }
    },
    "ทุ่งสง": {
        th: { problems: ["โรงงานปูนซีเมนต์", "โรงโม่หิน", "รถบรรทุกขนส่ง"], solutions: ["ติดตั้งระบบดักจับฝุ่น", "ฉีดพ่นน้ำลดฝุ่น", "ควบคุมรถบรรทุก"] },
        en: { problems: ["Cement factories particulate load", "Rock crushing mill operations", "Heavy haulage freight transport"], solutions: ["Install modern electrostatic precipitators", "Operate automated water sprays", "Restrict truck weights and speeds"] }
    },
    "ร่อนพิบูลย์": {
        th: { problems: ["โรงงานปูนซีเมนต์", "โรงโม่หิน", "การระเบิดหินปูน"], solutions: ["ควบคุมการระเบิดหิน", "ติดตั้งระบบกรองฝุ่น", "ตรวจวัดคุณภาพอากาศอย่างต่อเนื่อง"] },
        en: { problems: ["Cement production emissions", "Quarry stone crushing activities", "Limestone blasting operations"], solutions: ["Enforce blast-zone dust suppressants", "Fit heavy-duty dust collectors", "Maintain real-time ambient air tracking"] }
    },
    "ทุ่งใหญ่": {
        th: { problems: ["โรงเลื่อยไม้", "การเผาขยะ"], solutions: ["ควบคุมฝุ่นจากโรงเลื่อย", "งดการเผาขยะ", "ส่งเสริมการคัดแยกขยะ"] },
        en: { problems: ["Sawmill wood dust emissions", "Municipal solid waste burning"], solutions: ["Regulate sawmill sawdust collection", "Enact strict zero trash-burning bans", "Incentivize local waste sorting systems"] }
    },
    "ชะอวด": {
        th: { problems: ["การเผาใบยางพารา", "ไฟป่าพรุ", "ฝุ่นควันข้ามพื้นที่"], solutions: ["งดการเผาใบยาง", "จัดทำแนวกันไฟ", "เฝ้าระวังไฟป่าพรุ"] },
        en: { problems: ["Burning rubber plantation leaves", "Peat swamp forest fires", "Transboundary haze accumulation"], solutions: ["Ban dry rubber leaf burnings", "Excavate comprehensive peat firebreaks", "Deploy drone-assisted swamp fire watch"] }
    },
    "บางขัน": {
        th: { problems: ["การเผาใบยางพารา", "ฝุ่นจากกิจกรรมเกษตร"], solutions: ["ส่งเสริมเกษตรปลอดการเผา", "ทำปุ๋ยหมักจากเศษพืช", "ลดการใช้สารเคมี"] },
        en: { problems: ["Rubber tree leaf burning", "Dust from agricultural machinery"], solutions: ["Nurture smog-free smart farms", "Reclaim fallen leaves for compost", "Limit broad-spectrum farm chemicals"] }
    },
    "นาบอน": {
        th: { problems: ["การเผาเศษวัสดุทางการเกษตร", "ฝุ่นจากการทำเกษตร"], solutions: ["งดการเผาในพื้นที่เกษตร", "ส่งเสริมการใช้ประโยชน์จากเศษวัสดุเหลือใช้", "ลดการใช้สารเคมี"] },
        en: { problems: ["Agricultural waste burning", "Soil preparation dust"], solutions: ["Ban stubble field burning", "Turn harvest biomass into green products", "Lower dependent use of agri-chemicals"] }
    },
    "พระพรหม": {
        th: { problems: ["การเผาฟางข้าวหลังเก็บเกี่ยว", "ฝุ่นจากการเกษตร"], solutions: ["ส่งเสริมการไถกลบตอซัง", "งดเผาฟางข้าว", "เพิ่มพื้นที่สีเขียว"] },
        en: { problems: ["Post-harvest rice straw burning", "Agricultural tilling dust"], solutions: ["Encourage eco-stubble plowing techniques", "Stop burning straw left in paddies", "Create community defensive tree belts"] }
    },
    "เฉลิมพระเกียรติ": {
        th: { problems: ["การเผาฟางข้าวและเศษวัสดุทางการเกษตร", "ฝุ่นจากกิจกรรมเกษตร"], solutions: ["ส่งเสริมเกษตรปลอดการเผา", "ผลิตปุ๋ยหมักจากเศษพืช", "รณรงค์ลดการเผาในชุมชน"] },
        en: { problems: ["Rice straw and crop residue burning", "General farming activities dust"], solutions: ["Build zero-burn model farming towns", "Upcycle crop waste into bio-fertilizers", "Host widespread clean-air community rallies"] }
    }
};

// ==========================================
// 1. ระบบสลับภาษา (TH / EN Localization)
// ==========================================
let currentLang = 'th'; 

const amphoeNamesEN = {
    "เมือง": "Mueang", "พรหมคีรี": "Phrom Khiri", "ลานสกา": "Lan Saka", "ฉวาง": "Chawang",
    "พิปูน": "Phipun", "เชียรใหญ่": "Chian Yai", "ชะอวด": "Cha-uat", "ท่าศาลา": "Tha Sala",
    "ทุ่งสง": "Thung Song", "นาบอน": "Nabon", "ทุ่งใหญ่": "Thung Yai", "ปากพนัง": "Pak Phanang",
    "ร่อนพิบูลย์": "Ron Phibun", "สิชล": "Sichon", "ขนอม": "Khanom", "หัวไทร": "Hua Sai",
    "บางขัน": "Bang Khan", "ถ้ำพรรณรา": "Tham Phannara", "จุฬาภรณ์": "Chulabhorn", "พระพรหม": "Phra Phrom",
    "นบพิตำ": "Nopphitam", "ช้างกลาง": "Chang Klang", "เฉลิมพระเกียรติ": "Chaloem Phra Kiat"
};

const translations = {
    th: {
        navHome: "🏠 หน้าแรก", navAir: "📊 ข้อมูลคุณภาพอากาศ", navMap: "🗺️ แผนที่มลพิษ",
        heroTitle: "อากาศบริสุทธิ์<br>เพื่อชุมชนสุขภาพดี",
        heroDesc: "นวัตกรรมระบบฐานข้อมูลภูมิสารสนเทศและการรายงานสถิติฝุ่นละอองขนาดเล็กเรียลไทม์ ครอบคลุมพื้นที่ทั้ง 23 อำเภอ ขับเคลื่อนการเฝ้าระวังโดยเครือข่ายโรงเรียนในจังหวัดนครศรีธรรมราช",
        btnExplore: "🔍 ตรวจสอบรายอำเภอ", btnMap: "🗺️ เปิดแผนที่ขนาดใหญ่",
        dashTitle1: "🌍 สถานการณ์ภาพรวมจังหวัด", dashDesc1: "ค่าเฉลี่ยฝุ่นรวมทั้งจังหวัด",
        dashUpdate: "📍 ข้อมูลอัปเดต: เรียลไทม์จากระบบเครือข่าย", dashCover: "👥 ครอบคลุมพื้นที่การประมวลผล: ทั้ง 23 อำเภอ",
        dashTitle2: "⚠️ พื้นที่เฝ้าระวังค่าฝุ่นสูงสุด (Top 3)",
        airTitle: "📊 รายงานสถานการณ์ฝุ่นรายอำเภอ", airDesc: "เลือกอำเภอที่คุณต้องการตรวจสอบเพื่อฟังสรุปผลวิเคราะห์จากน้อง Wisdom Owl",
        airLabel: "📌 เลือกอำเภอในจังหวัดนครศรีธรรมราช:", defaultOpt: "-- กรุณาเลือกอำเภอ --",
        defaultText: "กรุณาเลือกอำเภอทางด้านซ้าย เพื่อให้น้อง Wisdom Owl เริ่มทำการวิเคราะห์สภาพอากาศและอ่านสคริปต์คำแนะนำให้ฟังค่ะ...",
        btnSpeakIdle: "🔊 กดเพื่อฟังการวิเคราะห์จากนกฮูก", btnSpeakActive: "🛑 กดเพื่อหยุดพูด",
        mapTitle: "🗺️ แผนที่พิกัดความหนาแน่นเชิงพื้นที่", mapDesc: "แสดงการกระจายตัวของมลพิษและฝุ่นละออง PM2.5 แบบเรียลไทม์",
        footerDesc: "พัฒนาขึ้นเพื่อสืบสานนวัตกรรมข้อมูลสุขภาพของชุมชนและโรงเรียนในพื้นที่"
    },
    en: {
        navHome: "🏠 Home", navAir: "📊 Air Quality", navMap: "🗺️ Dust Map",
        heroTitle: "Clean Air<br>For a Healthy Community",
        heroDesc: "An innovative real-time PM2.5 geospatial database and reporting system covering all 23 districts, driven by the local school network in Nakhon Si Thammarat.",
        btnExplore: "🔍 Check by District", btnMap: "🗺️ Open Large Map",
        dashTitle1: "🌍 Provincial Overview", dashDesc1: "Average PM2.5 across the province",
        dashUpdate: "📍 Last Updated: Real-time from the network", dashCover: "👥 Coverage: All 23 Districts",
        dashTitle2: "⚠️ Top 3 Monitored Areas",
        airTitle: "📊 District Air Quality Report", airDesc: "Select a district to check and listen to Wisdom Owl's analysis.",
        airLabel: "📌 Select a district in Nakhon Si Thammarat:", defaultOpt: "-- Please select a district --",
        defaultText: "Please select a district on the left so Wisdom Owl can analyze the air quality and read the recommendations for you...",
        btnSpeakIdle: "🔊 Listen to Owl's analysis", btnSpeakActive: "🛑 Stop speaking",
        mapTitle: "🗺️ Spatial Density Map", mapDesc: "Real-time PM2.5 pollution distribution map",
        footerDesc: "Developed to sustain health data innovation for local communities and schools."
    }
};

const textMappings = {
    'nav-home': 'navHome', 'nav-air': 'navAir', 'nav-map': 'navMap',
    'hero-title': 'heroTitle', 'hero-desc': 'heroDesc', 'btn-explore': 'btnExplore', 'btn-map': 'btnMap',
    'dash-title1': 'dashTitle1', 'dash-desc1': 'dashDesc1', 'dash-update': 'dashUpdate', 'dash-cover': 'dashCover',
    'dash-title2': 'dashTitle2', 'air-title': 'airTitle', 'air-desc': 'airDesc', 'air-label': 'airLabel',
    'map-title': 'mapTitle', 'map-desc': 'mapDesc', 'footer-desc': 'footerDesc'
};

function switchLanguage(lang) {
    currentLang = lang;
    const data = translations[lang];

    // เปลี่ยนคำทั่วไปทั้งหมด
    for (const [id, key] of Object.entries(textMappings)) {
        const el = document.getElementById(id);
        if (el) {
            if (id === 'hero-title' || id === 'hero-desc') el.innerHTML = data[key];
            else el.innerText = data[key];
        }
    }

    // อัปเดตรายชื่ออำเภอในช่อง Select
    const select = document.getElementById("amphoe-select");
    if (select) {
        select.options[0].innerText = data.defaultOpt;
        for (let i = 1; i < select.options.length; i++) {
            let val = select.options[i].value;
            let prefix = val === "เมือง" ? "" : "▲ ";
            select.options[i].innerText = lang === 'en' ? `${prefix}${amphoeNamesEN[val]} District` : `${prefix}อำเภอ${val}`;
        }
    }

    // เปลี่ยนสีปุ่มเมนู
    const btnTh = document.getElementById("btn-th"); const btnEn = document.getElementById("btn-en");
    if (lang === 'th') {
        if(btnTh) { btnTh.style.background = "#2563eb"; btnTh.style.color = "white"; }
        if(btnEn) { btnEn.style.background = "transparent"; btnEn.style.color = "#64748b"; }
    } else {
        if(btnEn) { btnEn.style.background = "#2563eb"; btnEn.style.color = "white"; }
        if(btnTh) { btnTh.style.background = "transparent"; btnTh.style.color = "#64748b"; }
    }

    // อัปเดตข้อมูลแดชบอร์ด
    if (cachedDashData) renderDashboard(cachedDashData.avgPM, cachedDashData.top3);

    // อัปเดตข้อมูลกล่องนกฮูกและตารางวิเคราะห์ถ้าเลือกอำเภอไว้แล้ว
    if (select && select.value && cachedAmphoeData[select.value]) {
        renderSelectedAmphoe(select.value, cachedAmphoeData[select.value]);
    } else {
        const textEl = document.getElementById('protection-text');
        if (textEl) textEl.innerText = data.defaultText;
        const engElement = document.getElementById('protection-text-en');
        if (engElement) engElement.style.display = 'none';
        
        const btnSpeak = document.getElementById("btn-speak");
        if (btnSpeak && !window.speechSynthesis.speaking) btnSpeak.innerHTML = data.btnSpeakIdle;
    }
}

// ==========================================
// 2. ระบบลูกเล่นย้ายหน้าต่างจำลอง (Tab Switcher)
// ==========================================
const navLinks = document.querySelectorAll('nav a.nav-link');
const sections = document.querySelectorAll('.content-section');

navLinks.forEach(link => {
    link.addEventListener('click', function(e) {
        e.preventDefault();
        const targetSectionId = this.getAttribute('href');
        switchToTab(targetSectionId);
    });
});

function switchToTab(targetId) {
    navLinks.forEach(item => {
        if (item.getAttribute('href') === targetId) item.classList.add('active');
        else item.classList.remove('active');
    });

    sections.forEach(section => {
        if ('#' + section.id === targetId) {
            section.style.display = 'block';
            if (targetId === '#map-section' && window.airwiseMap) setTimeout(() => { window.airwiseMap.invalidateSize(); }, 100);
        } else {
            section.style.display = 'none';
        }
    });
}

// ==========================================
// 3. ข้อมูลพิกัดและระบบเชื่อมต่อ API 
// ==========================================
const OPENWEATHER_API_KEY = '403eca128baf67c32147f04fe74a8a71'; 
const amphoeCoordinates = {
    "เมือง": { lat: 8.4304, lon: 99.9631 }, "พรหมคีรี": { lat: 8.5441, lon: 99.8242 }, "ลานสกา": { lat: 8.3516, lon: 99.7891 }, "ฉวาง": { lat: 8.4411, lon: 99.5019 },
    "พิปูน": { lat: 8.5639, lon: 99.5936 }, "เชียรใหญ่": { lat: 8.1883, lon: 100.1283 }, "ชะอวด": { lat: 7.9644, lon: 99.9983 }, "ท่าศาลา": { lat: 8.6677, lon: 99.9197 },
    "ทุ่งสง": { lat: 8.1642, lon: 99.6811 }, "นาบอน": { lat: 8.2575, lon: 99.5997 }, "ทุ่งใหญ่": { lat: 8.2939, lon: 99.3814 }, "ปากพนัง": { lat: 8.3547, lon: 100.1972 },
    "ร่อนพิบูลย์": { lat: 8.1814, lon: 99.8519 }, "สิชล": { lat: 9.0069, lon: 99.9161 }, "ขนอม": { lat: 9.2047, lon: 99.8583 }, "หัวไทร": { lat: 8.0419, lon: 100.2797 },
    "บางขัน": { lat: 8.0194, lon: 99.4636 }, "ถ้ำพรรณรา": { lat: 8.4194, lon: 99.3919 }, "จุฬาภรณ์": { lat: 8.0664, lon: 99.8731 }, "พระพรหม": { lat: 8.3664, lon: 99.9431 },
    "นบพิตำ": { lat: 8.7183, lon: 99.7567 }, "ช้างกลาง": { lat: 8.3619, lon: 99.5694 }, "เฉลิมพระเกียรติ": { lat: 8.1831, lon: 100.0631 }
};

let cachedAmphoeData = {}; 

const amphoeSelect = document.getElementById('amphoe-select');
if (amphoeSelect) {
    amphoeSelect.addEventListener('change', async function() {
        const selectedAmphoe = this.value;
        const coords = amphoeCoordinates[selectedAmphoe];
        if (!coords) return;

        if (cachedAmphoeData[selectedAmphoe]) {
            renderSelectedAmphoe(selectedAmphoe, cachedAmphoeData[selectedAmphoe]);
            return;
        }

        document.getElementById('pm-num').innerText = "...";
        document.getElementById('pm-badge').innerText = currentLang === 'en' ? "Updating..." : "กำลังอัปเดต...";
        document.getElementById('pm-badge').style.backgroundColor = "#cbd5e1";
        document.getElementById('air-result-card').style.display = "block";

        try {
            const response = await fetch(`https://api.openweathermap.org/data/2.5/air_pollution?lat=${coords.lat}&lon=${coords.lon}&appid=${OPENWEATHER_API_KEY}`);
            const data = await response.json();
            const pm25Value = Math.round(data.list[0].components.pm2_5);
            
            cachedAmphoeData[selectedAmphoe] = pm25Value;
            renderSelectedAmphoe(selectedAmphoe, pm25Value);
        } catch (error) {
            console.error(error);
            document.getElementById('pm-num').innerText = "Error";
        }
    });
}

function renderSelectedAmphoe(selectedAmphoe, pm25Value) {
    // 1. อัปเดตข้อมูลกล่องหลัก
    document.getElementById('selected-amphoe-title').innerText = currentLang === 'en' ? `${amphoeNamesEN[selectedAmphoe]} District` : `อำเภอ${selectedAmphoe}`;
    document.getElementById('pm-num').innerText = pm25Value;
    document.getElementById('air-result-card').style.display = "block";

    let statusText = ""; let statusColor = ""; let adviceScript = ""; let adviceScriptEn = "";

    if (pm25Value <= 15) {
        statusText = currentLang === 'en' ? "Excellent" : "อากาศดีมาก"; statusColor = "#10b981";
        adviceScript = `ขณะนี้อำเภอ${selectedAmphoe} มีปริมาณฝุ่นเพียง ${pm25Value} ไมโครกรัมต่อลูกบาศก์เมตร สภาพอากาศบริสุทธิ์ดีเยี่ยมค่ะ เหมาะสมกับการทำกิจกรรมกลางแจ้งได้อย่างปลอดภัยหายห่วงเลยนะคะ`;
        adviceScriptEn = `Currently, the PM 2.5 level in ${amphoeNamesEN[selectedAmphoe]} is ${pm25Value} micrograms per cubic meter. The air quality is excellent. It is perfectly safe to enjoy outdoor activities.`;
    } else if (pm25Value <= 37.5) {
        statusText = currentLang === 'en' ? "Moderate" : "อากาศปานกลาง"; statusColor = "#f59e0b";
        adviceScript = `ตรวจสอบพบปริมาณฝุ่นที่อำเภอ${selectedAmphoe} อยู่ที่ ${pm25Value} ไมโครกรัมต่อลูกบาศก์เมตร สภาพอากาศอยู่ในเกณฑ์ปานกลางค่ะ ประชาชนทั่วไปใช้ชีวิตได้ตามปกติ แต่สำหรับกลุ่มเสี่ยงควรลดระยะเวลาทำกิจกรรมกลางแจ้งลงนิดหน่อยนะคะ`;
        adviceScriptEn = `The PM 2.5 level in ${amphoeNamesEN[selectedAmphoe]} is ${pm25Value} micrograms per cubic meter. The air quality is moderate. The general public can go about normal lives, but sensitive groups should reduce outdoor activities.`;
    } else {
        statusText = currentLang === 'en' ? "Unhealthy" : "เริ่มมีผลกระทบ"; statusColor = "#ef4444";
        adviceScript = `แจ้งเตือนค่ะ! อำเภอ${selectedAmphoe} มีปริมาณฝุ่นสูงถึง ${pm25Value} ไมโครกรัมต่อลูกบาศก์เมตร เริ่มมีผลกระทบต่อสุขภาพแล้ว แนะนำให้หลีกเลี่ยงกิจกรรมกลางแจ้ง และอย่าลืมสวมหน้ากากอนามัยป้องกันฝุ่นทุกครั้งนะคะ`;
        adviceScriptEn = `Warning! The PM 2.5 level in ${amphoeNamesEN[selectedAmphoe]} is as high as ${pm25Value} micrograms per cubic meter. This is unhealthy. Please avoid outdoor activities and always wear a mask.`;
    }

    document.getElementById('pm-badge').innerText = statusText;
    document.getElementById('pm-badge').style.backgroundColor = statusColor;

    // 2. อัปเดตข้อมูลกล่องปัญหาและวิธีแก้ไข (Insights) เข้า HTML
    const insightsCard = document.getElementById('district-insights-card');
    const problemsList = document.getElementById('insight-problems-list');
    const solutionsList = document.getElementById('insight-solutions-list');
    const problemTitle = document.getElementById('insight-problem-title');
    const solutionTitle = document.getElementById('insight-solution-title');

    if (insightsCard && problemsList && solutionsList) {
        const info = districtInsightsData[selectedAmphoe];
        
        if (info) {
            problemsList.innerHTML = '';
            solutionsList.innerHTML = '';

            if (currentLang === 'en') {
                problemTitle.textContent = "Local Key Issues";
                solutionTitle.textContent = "Solutions & Prevention";
            } else {
                problemTitle.textContent = "ปัญหาหลักในพื้นที่";
                solutionTitle.textContent = "แนวทางแก้ไขและป้องกัน";
            }

            info[currentLang].problems.forEach(item => {
                const li = document.createElement('li');
                li.style.marginBottom = '0.35rem';
                li.innerHTML = `<i class="fa-solid fa-circle-minus" style="color:#ef4444; font-size:0.75rem; margin-right:8px;"></i> ${item}`;
                problemsList.appendChild(li);
            });

            info[currentLang].solutions.forEach(item => {
                const li = document.createElement('li');
                li.style.marginBottom = '0.35rem';
                li.innerHTML = `<i class="fa-solid fa-circle-check" style="color:#10b981; font-size:0.75rem; margin-right:8px;"></i> ${item}`;
                solutionsList.appendChild(li);
            });

            insightsCard.style.display = 'block';
        } else {
            insightsCard.style.display = 'none';
        }
    }

    // 3. จัดการนกฮูก
    const analysisZone = document.getElementById('analysis-zone');
    analysisZone.style.opacity = "1"; analysisZone.style.pointerEvents = "auto";
    
    let engElement = document.getElementById('protection-text-en');
    if (!engElement) {
        engElement = document.createElement('p');
        engElement.id = 'protection-text-en';
        engElement.style.color = '#2563eb';
        engElement.style.marginTop = '12px';
        engElement.style.fontStyle = 'italic';
        engElement.style.fontWeight = '500';
        document.getElementById('protection-text').parentNode.appendChild(engElement);
    }

    if (currentLang === 'en') {
        document.getElementById('protection-text').innerText = adviceScriptEn;
        engElement.style.display = 'none'; 
    } else {
        document.getElementById('protection-text').innerText = adviceScript;
        engElement.style.display = 'block'; 
        engElement.innerText = "🇬🇧 " + adviceScriptEn;
    }

    const btnSpeak = document.getElementById('btn-speak');
    btnSpeak.disabled = false;
    if (window.speechSynthesis) window.speechSynthesis.cancel();
    document.getElementById('character-img').src = 'assets/character-idle.png';
    btnSpeak.innerHTML = translations[currentLang].btnSpeakIdle;
}

// ==========================================
// 4. ฟังก์ชันดึงข้อมูล "ภาพรวมจังหวัด"
// ==========================================
let cachedDashData = null; 

async function loadDashboardData() {
    if (!OPENWEATHER_API_KEY || OPENWEATHER_API_KEY === 'วางรหัส API KEY ของคุณตรงนี้') return;
    if (cachedDashData) { renderDashboard(cachedDashData.avgPM, cachedDashData.top3); return; }

    const sampleAmphoes = ["เมือง", "ทุ่งสง", "ท่าศาลา", "ปากพนัง", "สิชล", "หัวไทร"];
    let totalPM = 0; let count = 0; let rankList = [];

    for (let name of sampleAmphoes) {
        try {
            const coords = amphoeCoordinates[name];
            const response = await fetch(`https://api.openweathermap.org/data/2.5/air_pollution?lat=${coords.lat}&lon=${coords.lon}&appid=${OPENWEATHER_API_KEY}`);
            const data = await response.json();
            const pm25 = Math.round(data.list[0].components.pm2_5);
            totalPM += pm25; count++; rankList.push({ name: name, pm: pm25 });
        } catch (e) { console.log("Error fetching ranking for " + name); }
    }

    if (count > 0) {
        const avgPM = Math.round(totalPM / count);
        rankList.sort((a, b) => b.pm - a.pm); 
        const top3 = rankList.slice(0, 3);
        cachedDashData = { avgPM, top3 };
        renderDashboard(avgPM, top3);
    }
}

function renderDashboard(avgPM, top3) {
    document.getElementById('avg-pm-display').innerHTML = `${avgPM} <span style="font-size: 1.2rem;">µg/m³</span>`;
    const badge = document.getElementById('avg-status-badge');
    const card = document.getElementById('provincial-card');
    
    if (avgPM <= 15) {
        badge.innerText = currentLang === 'en' ? "Excellent" : "ภาพรวมดีมาก"; 
        card.style.backgroundColor = "#10b981";
    } else if (avgPM <= 37.5) {
        badge.innerText = currentLang === 'en' ? "Moderate" : "ภาพรวมปานกลาง"; 
        card.style.backgroundColor = "#f59e0b";
    } else {
        badge.innerText = currentLang === 'en' ? "Unhealthy" : "เริ่มมีผลกระทบ"; 
        card.style.backgroundColor = "#ef4444";
    }

    let listHTML = "";
    let prefixRank = currentLang === 'en' ? "Rank" : "อันดับ";
    let prefixAmphoe = currentLang === 'en' ? "District" : "อำเภอ";

    top3.forEach((item, index) => {
        let color = index === 0 ? "#ef4444" : (index === 1 ? "#f59e0b" : "#3b82f6");
        let name = currentLang === 'en' ? amphoeNamesEN[item.name] : item.name;
        let displayStr = currentLang === 'en' ? `🛑 ${prefixRank} ${index+1} : ${name} ${prefixAmphoe}` : `🛑 ${prefixRank} ${index+1} : ${prefixAmphoe}${name}`;
        
        listHTML += `
            <div style="display: flex; justify-content: space-between; align-items: center; background: #f8fafc; padding: 0.8rem 1rem; border-radius: 8px; border-left: 4px solid ${color};">
                <span style="font-weight: 500;">${displayStr}</span>
                <span style="font-weight: 600; color: ${color};">${item.pm} µg/m³</span>
            </div>
        `;
    });
    document.getElementById('top-dangerous-list').innerHTML = listHTML;
}

// ==========================================
// 5. ระบบเสียงอ่านพากย์ตัวละคร + ขยับปาก
// ==========================================
const btnSpeak = document.getElementById('btn-speak');
let mouthAnimationInterval = null; 
let isMouthOpen = false;

if (btnSpeak && 'speechSynthesis' in window) {
    
    function doMouthToggling() {
        const charImg = document.getElementById('character-img');
        if (!charImg) return;
        
        if (window.speechSynthesis.speaking) {
            charImg.src = isMouthOpen ? 'assets/character-idle.png' : 'assets/character-talking.png';
            isMouthOpen = !isMouthOpen;
        }
    }

    function stopMouthAndReset() {
        if (mouthAnimationInterval) {
            clearInterval(mouthAnimationInterval);
            mouthAnimationInterval = null;
        }
        const charImg = document.getElementById('character-img');
        if (charImg) charImg.src = 'assets/character-idle.png';
        isMouthOpen = false;
        btnSpeak.innerHTML = translations[currentLang].btnSpeakIdle;
    }

    btnSpeak.addEventListener('click', () => {
        if (window.speechSynthesis.speaking) {
            window.speechSynthesis.cancel();
            stopMouthAndReset();
            return;
        }
        
        let textToSpeak = "";
        const utterance = new SpeechSynthesisUtterance();

        if (currentLang === 'en') {
            textToSpeak = document.getElementById('protection-text').innerText;
        } else {
            const engElement = document.getElementById('protection-text-en');
            if (!engElement) return;
            textToSpeak = engElement.innerText.replace("🇬🇧 ", "");
        }
        
        utterance.text = textToSpeak;
        utterance.lang = 'en-US'; 
        utterance.rate = 0.85;  
        utterance.volume = 1.0; 

        const availableVoices = window.speechSynthesis.getVoices();
        const engVoice = availableVoices.find(v => v.lang === 'en-US' || v.lang.includes('en'));
        if (engVoice) utterance.voice = engVoice;

        utterance.onstart = () => {
            btnSpeak.innerHTML = translations[currentLang].btnSpeakActive;
            if (mouthAnimationInterval) clearInterval(mouthAnimationInterval);
            mouthAnimationInterval = setInterval(doMouthToggling, 350);
        };

        utterance.onend = stopMouthAndReset;
        utterance.onerror = (event) => {
            console.error('Speech Error:', event);
            stopMouthAndReset();
        };

        window.speechSynthesis.cancel();
        window.speechSynthesis.speak(utterance);
    });
}

if ('speechSynthesis' in window) {
    window.speechSynthesis.getVoices();
    if (window.speechSynthesis.onvoiceschanged !== undefined) {
        window.speechSynthesis.onvoiceschanged = () => { window.speechSynthesis.getVoices(); };
    }
}

// ==========================================
// 6. ระบบแผนที่พื้นฐาน + แสดงจุดค่าฝุ่นทุกอำเภอ
// ==========================================
async function initMap() {
    const nakhonLatLong = [8.4304, 99.9631];
    const map = L.map('map').setView(nakhonLatLong, 9);
    window.airwiseMap = map;
    
    L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
        subdomains: 'abcd',
        maxZoom: 20
    }).addTo(map);
    
    for (const [name, coords] of Object.entries(amphoeCoordinates)) {
        try {
            const response = await fetch(`https://api.openweathermap.org/data/2.5/air_pollution?lat=${coords.lat}&lon=${coords.lon}&appid=${OPENWEATHER_API_KEY}`);
            const data = await response.json();
            const pm25 = Math.round(data.list[0].components.pm2_5);
            
            cachedAmphoeData[name] = pm25;

            let color = "#10b981"; 
            let statusName = currentLang === 'en' ? "Excellent" : "ดีมาก";
            
            if (pm25 > 15 && pm25 <= 37.5) {
                color = "#f59e0b"; 
                statusName = currentLang === 'en' ? "Moderate" : "ปานกลาง";
            } else if (pm25 > 37.5) {
                color = "#ef4444"; 
                statusName = currentLang === 'en' ? "Unhealthy" : "เริ่มมีผลกระทบ";
            }

            L.circle([coords.lat, coords.lon], {
                color: color,
                fillColor: color,
                fillOpacity: 0.4,
                radius: 4500 
            }).addTo(map).bindPopup(`
                <div style="font-family: 'Kanit', sans-serif; direction: ltr; text-align: left;">
                    <strong style="font-size: 1rem; color: #1e293b;">
                        ${currentLang === 'en' ? 'District: ' + (amphoeNamesEN[name] || name) : 'อำเภอ' + name}
                    </strong>
                    <div style="margin-top: 5px; font-size: 0.9rem;">
                        <b>PM2.5:</b> <span style="color:${color}; font-weight:bold;">${pm25} µg/m³</span><br>
                        <b>${currentLang === 'en' ? 'Status' : 'สถานะ'}:</b> <span style="color:${color}; font-weight:bold;">${statusName}</span>
                    </div>
                </div>
            `);

            const textIcon = L.divIcon({
                className: 'map-dust-number',
                html: `<div style="background-color: ${color}; color: white; font-weight: bold; font-family: 'Kanit', sans-serif; padding: 2px 6px; border-radius: 8px; font-size: 11px; box-shadow: 0 2px 6px rgba(0,0,0,0.2); white-space: nowrap;">${pm25}</div>`,
                iconSize: [25, 20],
                iconAnchor: [12, 10] 
            });
            
            L.marker([coords.lat, coords.lon], { icon: textIcon }).addTo(map)
                .bindPopup(`<b>${currentLang === 'en' ? (amphoeNamesEN[name] || name) : 'อำเภอ' + name}</b>: ${pm25} µg/m³`);

        } catch (error) {
            console.error(`ไม่สามารถโหลดข้อมูลแผนที่ของอำเภอ ${name} ได้:`, error);
        }
    }
}

// ========================================================
// 7. ระบบเริ่มต้นทำงานเมื่อโหลดหน้าเว็บ
// ========================================================
window.addEventListener('DOMContentLoaded', () => {
    initMap();
    loadDashboardData(); 
    
    const btnTh = document.getElementById("btn-th");
    const btnEn = document.getElementById("btn-en");
    if (btnTh) btnTh.addEventListener('click', () => switchLanguage('th'));
    if (btnEn) btnEn.addEventListener('click', () => switchLanguage('en'));

    const menuToggle = document.getElementById('menu-toggle');
    const navMenu = document.getElementById('nav-menu');
    
    if (menuToggle && navMenu) {
        menuToggle.addEventListener('click', (e) => {
            e.stopPropagation();
            menuToggle.classList.toggle('active');
            navMenu.classList.toggle('active');
        });
        
        document.querySelectorAll('#nav-menu .nav-link').forEach(link => {
            link.addEventListener('click', () => {
                menuToggle.classList.remove('active');
                navMenu.classList.remove('active');
            });
        });
    }

    const btnProducer = document.getElementById('btn-producer');
    const producerModal = document.getElementById('producer-modal');
    const closeProducer = document.getElementById('close-producer');

    if (btnProducer && producerModal && closeProducer) {
        btnProducer.addEventListener('click', () => { 
            producerModal.style.display = 'flex'; 
        });
        closeProducer.addEventListener('click', () => { 
            producerModal.style.display = 'none'; 
        });
        producerModal.addEventListener('click', (e) => { 
            if (e.target === producerModal) producerModal.style.display = 'none'; 
        });
    }
});